// scripts/sw-core.js
// Shared service-worker generator used by both origins:
//   - generate-sw.js          → the wallet origin
//   - generate-keyguard-sw.js → the keyguard origin
//
// Walks a tree, pins a SHA-256 per served file, and emits an sw.js that
// verifies those hashes on install (fail-closed) and on fetch. The only
// per-origin differences are the file tree, the EXCLUDE set, the CACHE_NAME
// prefix, and the cache-miss policy (see cacheOnly).

const { createHash } = require('node:crypto');
const { readFileSync, writeFileSync, readdirSync } = require('node:fs');
const { join, relative } = require('node:path');
const { execSync } = require('node:child_process');

function sha256File(filePath) {
    const buf = readFileSync(filePath);
    return `sha256-${createHash('sha256').update(buf).digest('base64')}`;
}

function walk(dir, excludes) {
    const out = [];
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (excludes.has(entry.name)) continue;
        const full = join(dir, entry.name);
        if (entry.isDirectory()) out.push(...walk(full, excludes));
        else if (entry.isFile()) out.push(full);
    }
    return out;
}

function gitVersion(cwd) {
    try {
        return execSync('git rev-parse --short HEAD', { cwd }).toString().trim();
    } catch {
        // No git (e.g. inside a one-shot container) — fall back to a timestamp.
        return Date.now().toString(36);
    }
}

function buildSwSource({ hashMap, version, cacheNamePrefix, cacheOnly }) {
    return `// AUTO-GENERATED — do not edit manually.
// Generated by scripts/sw-core.js. Version: ${version}
//
// Security guarantee: if any file on the server has a different hash than
// what is listed here, the SW install fails and the previous known-good SW
// continues serving users. Tampered files cannot reach returning visitors.

const CACHE_NAME = '${cacheNamePrefix}${version}';

// When true (keyguard): app code is served ONLY from the install-verified
// cache; a cache miss fails closed (reload re-installs) instead of touching
// the network at steady state. Large binaries are always allowed to refetch
// (see SKIP_REVERIFY) because a nested worker may fetch them uncached.
const CACHE_ONLY = ${cacheOnly ? 'true' : 'false'};

// SHA-256 hashes of every served file. Computed at deploy time.
const FILE_HASHES = ${JSON.stringify(hashMap, null, 4)};

// Derive path prefix from the SW's own URL (handles project-subpath deploys).
const BASE = self.location.pathname.replace(/sw\\.js$/, '');

// ── Install: fetch all files, verify hashes, cache ───────────────────────
self.addEventListener('install', (event) => {
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE_NAME);
        for (const [relPath, expectedHash] of Object.entries(FILE_HASHES)) {
            const url = BASE + relPath;
            const response = await fetch(url, { cache: 'no-store' });
            if (!response.ok) {
                throw new Error(\`Fetch failed: \${url} (\${response.status})\`);
            }
            const buf = await response.arrayBuffer();
            const hashBuf = await crypto.subtle.digest('SHA-256', buf);
            const b64 = btoa(String.fromCharCode(...new Uint8Array(hashBuf)));
            const actualHash = \`sha256-\${b64}\`;
            if (actualHash !== expectedHash) {
                throw new Error(
                    \`Hash mismatch for \${url}\\nExpected: \${expectedHash}\\nActual:   \${actualHash}\`
                );
            }
            await cache.put(url, new Response(buf, {
                status: response.status,
                statusText: response.statusText,
                headers: response.headers,
            }));
        }
        await self.skipWaiting();
    })());
});

// ── Activate: remove stale caches, claim all clients ─────────────────────
self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const keys = await caches.keys();
        await Promise.all(
            keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k))
        );
        await self.clients.claim();
    })());
});

// ── Fetch: cache-first with hash re-verification ─────────────────────────
// Skip re-verification for large binary files (.wasm, the vendored ethers
// bundle) that were already verified at install time — hashing multi-MB
// files on every fetch adds noticeable latency.
const SKIP_REVERIFY = new Set(
    Object.keys(FILE_HASHES).filter(p => p.endsWith('.wasm') || p.endsWith('ethers.esm.min.js')),
);

self.addEventListener('fetch', (event) => {
    if (event.request.method !== 'GET') return;
    const url = new URL(event.request.url);
    if (url.origin !== self.location.origin) return;

    const relPath = url.pathname.startsWith(BASE)
        ? url.pathname.slice(BASE.length)
        : null;
    if (!relPath || !(relPath in FILE_HASHES)) return;

    event.respondWith((async () => {
        const cache = await caches.open(CACHE_NAME);
        const cached = await cache.match(event.request);
        if (cached) {
            if (SKIP_REVERIFY.has(relPath)) return cached;

            const buf = await cached.clone().arrayBuffer();
            const hashBuf = await crypto.subtle.digest('SHA-256', buf);
            const b64 = btoa(String.fromCharCode(...new Uint8Array(hashBuf)));
            const actualHash = \`sha256-\${b64}\`;
            if (actualHash === FILE_HASHES[relPath]) {
                return cached;
            }
            await cache.delete(event.request);
            return new Response('Integrity check failed', {
                status: 500, statusText: 'Integrity Error',
            });
        }
        // Cache miss. In cache-only mode (keyguard), app code is never
        // re-fetched at runtime — fail closed so a reload re-installs and
        // re-verifies. Large binaries always fall through to verified refetch.
        if (CACHE_ONLY && !SKIP_REVERIFY.has(relPath)) {
            return new Response('Cache unavailable — reload to re-initialize', {
                status: 503, statusText: 'Reload Required',
            });
        }
        const response = await fetch(event.request);
        if (!response.ok) return response;
        const buf = await response.arrayBuffer();
        const hashBuf = await crypto.subtle.digest('SHA-256', buf);
        const b64 = btoa(String.fromCharCode(...new Uint8Array(hashBuf)));
        const actualHash = \`sha256-\${b64}\`;
        if (actualHash !== FILE_HASHES[relPath]) {
            return new Response('Integrity check failed', {
                status: 500, statusText: 'Integrity Error',
            });
        }
        const verified = new Response(buf, {
            status: response.status,
            statusText: response.statusText,
            headers: response.headers,
        });
        await cache.put(event.request, verified.clone());
        return verified;
    })());
});
`;
}

/**
 * Walk rootDir, hash every non-excluded file, and write an integrity-pinned
 * service worker to outFile.
 * @returns {{count:number, version:string}}
 */
function generateServiceWorker({ rootDir, excludes, outFile, cacheNamePrefix, cacheOnly = false }) {
    const files = walk(rootDir, excludes).sort();
    const hashMap = Object.fromEntries(
        files.map(f => [relative(rootDir, f).replace(/\\/g, '/'), sha256File(f)]),
    );
    const version = gitVersion(rootDir);
    writeFileSync(outFile, buildSwSource({ hashMap, version, cacheNamePrefix, cacheOnly }), 'utf8');
    return { count: Object.keys(hashMap).length, version };
}

module.exports = { generateServiceWorker, sha256File, walk };
